### PR TITLE
Feat/map 187 map 188/full stack/added the ability to reply to comments

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by naberalgamma** [comment]
maybe add reply under comment?
image

**Review by Yojuks — CHANGES_REQUESTED** [review]
Screenshot 2022-06-27 at 21 07 32
why you decided do this task like a tree - maybe like a youtube?

**Review by Yojuks — COMMENTED** [review]
Screenshot 2022-06-27 at 21 11 45
there are so small letters i can add - change validation like a comment - 500

**Review by Yojuks — COMMENTED** [review]
and i think that usefully was reply buuton was next to date in one string or between date and like

**Comment by ananchenko346** [comment]
I can limit but let there be many levels of nesting.

**Comment by ghost** [comment]
> and i think that usefully was reply buuton was next to date in one string or between date and like

Ok, I'll take out the button.

**Comment by ghost** [comment]
> Screenshot 2022-06-27 at 21 07 32
> 
> why you decided do this task like a tree - maybe like a youtube?

I did it in the likeness of TJ. I can fix up to three levels, but it's more interesting that way.

**Comment by ghost** [comment]
> Screenshot 2022-06-27 at 21 11 45
> 
> there are so small letters i can add - change validation like a comment - 500

I'll fix this.

**Comment by ghost** [comment]
> maybe add reply under comment? image

Ok. I'll change this.

**Comment by ghost** [comment]
> > and i think that usefully was reply buuton was next to date in one string or between date and like
> 
> Ok, I'll take out the button.

I did it, but I think it's terrible.

**Review by obozhko-dev — APPROVED** [review]

**Comment by naberalgamma** [comment]
5 symbols maybe make 2 ? 
image

**Review by naberalgamma — CHANGES_REQUESTED** [review]
deleting comments broken, after click to delet comment, comment don't disapier but after refreshin page it gone
image

**Comment by ghost** [comment]
> deleting comments broken, after click to delet comment, comment don't disapier but after refreshin page it gone image

This is very strange since I'm currently testing and everything works fine

**Comment by naberalgamma** [comment]
> > deleting comments broken, after click to delet comment, comment don't disapier but after refreshin page it gone image
> 
> This is very strange since I'm currently testing and everything works fine
after restarting all work correct, sorry

**Review by naberalgamma — APPROVED** [review]

**Review by romawht22 — APPROVED** [review]

**Review by Yojuks — APPROVED** [review]

**Pull request merged**
