### PR TITLE
Fixed ability to add multiple locations

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by Yojuks — APPROVED** [review]

**Review by obozhko-dev — CHANGES_REQUESTED** [review]
When I added name, descriptiond, pictures and click to button "Done and submit" - I see error message in console and location not added 
Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
POST http://localhost:3001/api/locations/create 400 (Bad Request)
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'message')
image

**Comment by obozhko-dev** [comment]
> When I added name, descriptiond, pictures and click to button "Done and submit" - I see error message in console and location not added Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received POST http://localhost:3001/api/locations/create 400 (Bad Request) Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'message') image

I understand, description of this location was 274 symbols, in updateLocationLikesSchema in the backend validationSchemes.ts I found that isLength({ min: 10, max: 200 }) fot description. I cut description to 180 symbols (approximately) and it was saved . We have not friendly error message or ii is bug?

**Review by obozhko-dev — APPROVED** [review]

**Comment by ghost** [comment]
Again errors in redux.
I'll fix it later and post it as a separate pull request.

**Comment by ghost** [comment]
I fixed it

**Pull request merged**
