### PR TITLE
Feat/map 210/add about us screen

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by mazursasha1990 — COMMENTED** [review]
In my opinion, it is would be better to change the text-align in the description section
AboutUs
.

**Comment by ghost** [comment]
> In my opinion, it is would be better to change the text-align in the description section
> 
> AboutUs
> 
> .

Ok, I can change it but could you be more specific about text? I didn't understand you.

**Comment by mazursasha1990** [comment]
> about

In the image, it is my changes. In your version the field "text-align: left".
AboutUs2
But it is not critical.

**Comment by ghost** [comment]
> > about
> 
> In the image, it is my changes. In your version the field "text-align: left". AboutUs2 But it is not critical.

Ohh, I understood.
It's fixed.

**Review by mazursasha1990 — APPROVED** [review]

**Review by obozhko-dev — APPROVED** [review]

**Pull request merged**
